// actions
export const SET_WORK_EXPERIENCE = "SET_WORK_EXPERIENCE";
export const SET_EDUCATION_EXPERIENCE = "SET_EDUCATION_EXPERIENCE";
export const RESET = "RESET";

// mutations
export const SAVE_WORK_EXPERIENCE = "SAVE_WORK_EXPERIENCE";
export const SAVE_EDUCATION_EXPERIENCE = "SAVE_EDUCATION_EXPERIENCE";
export const SAVE_RESET = "SAVE_RESET";

// getters
export const WORK_EXPERIENCE = "WORK_EXPERIENCE";
export const EDUCATION_EXPERIENCE = "EDUCATION_EXPERIENCE";
